# Generated by Django 5.2.7 on 2025-10-28 14:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('c', 'C++'), ('an', 'Android')], max_length=20, verbose_name='Курс')),
                ('course_num', models.SmallIntegerField(default=1, verbose_name='Номер курса')),
                ('start_date', models.DateField(null=True, verbose_name='Начало курса')),
                ('end_date', models.DateField(null=True, verbose_name='Окончание курса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст')),
                ('sex', models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], max_length=10, verbose_name='Пол')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('course', models.ManyToManyField(blank=True, to='main.course', verbose_name='Курсы')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка')),
                ('date', models.DateField(null=True, verbose_name='Дата оценки')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.student')),
            ],
        ),
    ]
